### PR TITLE
Feature events

### PR DESCRIPTION
**Pull request by michaelamponsah**
In this branch, the following requirements have been implemented;

- [x] Used `state `and `props`, passed props to `child components`
- [x] Lifted state up to a common parent component
- [x] Implemented the logic to display and update the calculator display using `this.setState`

### CODE REVIEW

**Comment by thecodechaser** [comment]
@michaelamponsah check slack for my message.

**Review by Ghiftee — COMMENTED** [review]
Hi @michaelamponsah , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that does not have a professional README. Kindly update your README using [this template](https://github.com/microverseinc/readme-template). Remember to remove the Microverse logo, you can replace it with yours if you have one.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by michaelamponsah** [comment]
> Hi @michaelamponsah ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
>  [ 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a54375464357852716b76485176546445752f67697068792e676966 ](https://camo.githubusercontent.com/5c25b6dcafc40dba64eb256e9d4235f02496a4d0f3a8ca5f7cff3f8dce8a3442/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a54375464357852716b76485176546445752f67697068792e676966) [ ](https://camo.githubusercontent.com/5c25b6dcafc40dba64eb256e9d4235f02496a4d0f3a8ca5f7cff3f8dce8a3442/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a54375464357852716b76485176546445752f67697068792e676966)
> 
> ## Invalid Code Review Request
> You have submitted a project, that does not have a professional README. Kindly update your README using [this template](https://github.com/microverseinc/readme-template). Remember to remove the Microverse logo, you can replace it with yours if you have one.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @michaelamponsah, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All linters passing
- All requirements completed
- Professional readme

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
